name: release_docker

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*'

jobs:
  release_docker:
    name: Release Docker
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          go-version: 'stable'

      - name: Cache Musl
        id: cache-musl
        uses: actions/cache@v4
        with:
          path: build/musl-libs
          key: docker-musl-libs

      - name: Download Musl Library
        if: steps.cache-musl.outputs.cache-hit != 'true'
        run: bash build.sh prepare docker-multiplatform

      - name: Build go binary
        run: bash build.sh release docker-multiplatform

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: dragonssr/alist

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: dragonssr
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v6
        with:
          context: .
          file: Dockerfile.ci
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          platforms: linux/amd64,linux/arm64,linux/arm/v7,linux/386,linux/arm/v6,linux/s390x

      - name: Docker meta with ffmpeg
        id: meta-ffmpeg
        uses: docker/metadata-action@v5
        with:
          images: dragonssr/alist
          flavor: |
            latest=true
            suffix=-ffmpeg,onlatest=true
            
      - name: Build and push with ffmpeg
        id: docker_build_ffmpeg
        uses: docker/build-push-action@v6
        with:
          context: .
          file: Dockerfile.ci
          push: true
          tags: ${{ steps.meta-ffmpeg.outputs.tags }}
          labels: ${{ steps.meta-ffmpeg.outputs.labels }}
          build-args: INSTALL_FFMPEG=true
          platforms: linux/amd64,linux/arm64,linux/arm/v7,linux/386,linux/arm/v6,linux/s390x

  release_docker_with_aria2:
    needs: release_docker
    name: Release docker with aria2
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          repository: loognsss/with_aria2
          ref: main
          persist-credentials: false
          fetch-depth: 0

      - name: Add tag
        run: |
          git config --local user.email "2945065490@qq.com"
          git config --local user.name "Three-taile-dragon"
          git tag -a ${{ github.ref_name }} -m "release ${{ github.ref_name }}"

      - name: Push tags
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.MY_TOKEN }}
          branch: main
          repository: loognsss/with_aria2
